GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJGaXJtYW5zeWEgRmlsYXl1ZGEgLSAyIiwiZW1haWwiOiJmaWxheXVkYWZpcm1hbnN5YTJAZ21haWwuY29tIiwiaWF0IjoxNzEwMDYwODU0LCJleHAiOjE3MTAwNjA4NzR9.snK6hYOOovANTbJERBzaBrjfUsIGhj3PBzL4QpBaJ2Y


###

POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Firmansya Filayuda - 5",
    "email": "filayudafirmansya5@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}


###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "filayudafirmansya2@gmail.com",
    "password": "123456"
}

###
GET  http://localhost:5000/token
Content-Type: application/json


###
DELETE http://localhost:5000/logout 